import type { Metadata } from "next"
import NextTopLoader from "nextjs-toploader"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-white to-gray-200">
        <NextTopLoader color="#4f46e5" showSpinner={false} />
        {children}
      </body>
    </html>
  )
}
